### ISSUE TITLE
Couple of bugs in kubernetes.py

### ISSUE THREAD

**Issue by bolliger32** [RhodiumGroup/rhg_compute_tools#75]
- isintance instead of isinstance
- had not imported warnings

These were addressed in #71 which we are closing now so that we can first merge a purely black-only PR, and then we will again file a PR from the `autofmt` branch that specifically addresses these bugs and is easier to review

**Comment by delgadom** [comment]
thank you!

**Comment by delgadom** [comment]
#65 and #74 have been merged. PR away!
