### ISSUE TITLE
enforce isort and black in tests

### ISSUE THREAD

**Issue by bolliger32** [RhodiumGroup/rhg_compute_tools#77]
In order to keep things clean, we could add the following commands to our tests

```
isort --profile black -c .
black --check .
```

isort just makes imports slightly easier to follow (orders them by type of package and alphabetically, splits them into groups, and deletes duplicate imports). Not a big deal but why not make things a little cleaner.

**Comment by delgadom** [comment]
I dunno. this just adds another way to discourage contributions and break tests. we don't have that many contributors - you sure it's worth it? black seems fine. ok if we stick to that?

**Comment by bolliger32** [comment]
Sure sounds good. I'm not sure I agree that it discourages contributions but I don't really have a strong preference either way. Was just opening this to follow up on: https://github.com/RhodiumGroup/rhg_compute_tools/pull/71#pullrequestreview-447496921
