### ISSUE TITLE
switch from bumpversion to setuptools_scm

### ISSUE THREAD

**Issue by delgadom** [RhodiumGroup/rhg_compute_tools#78]
https://github.com/pypa/setuptools_scm

Features:
* Not deprecated

H/T @brews for the rec

**Comment by delgadom** [comment]
See [this](https://github.com/ClimateImpactLab/derive/commit/db1a49d63adc69f929507ec5d221ee559a224327) as an implementation example

**Comment by brews** [comment]
If need to keep a `__version__` attribute in your __init__.py, `xarray` has an example of doing this with `pkg_resources.get_distribution()` at https://github.com/pydata/xarray/blob/e1dafe676812409834ccac3418ecf47600b00615/xarray/__init__.py#L33
