### ISSUE TITLE
mpl 3.4 drops `font_manager._rebuild()` function and breaks `design` imports

### ISSUE THREAD

**Issue by bolliger32** [RhodiumGroup/rhg_compute_tools#96]
### Description

Our CI pipeline just broke and it's b/c matplotlib just released v3.4.0. In this version there is no more `_rebuild()` function within the [`matplotlib.font_manager` module](https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/font_manager.py). We call this function here: https://github.com/RhodiumGroup/rhg_compute_tools/blob/49d9f7bfec979454a58b4776ffb51f68328a850b/rhg_compute_tools/design/__init__.py#L29

It looks like the font loading lines above L129 are all commented out, so do we need this anymore? It wasn't immediately clear to me why matplotlib took it out or what the proper way to rebuild the font cache is now, but if we don't need it anymore we could remove that line. Until then, it's blocking as it breaks our CI

@delgadom do you know if we still need that `_rebuild` call?

**Comment by delgadom** [comment]
dang. no we don't
